[workspace]
# List of crates included in this workspace
members = [
    "arbiter-bindings",
    "arbiter-core",
    "arbiter-engine",
    "documentation",
]

# List of crates excluded from this workspace
exclude = ["benches"]

# Package configuration
[package]
name = "arbiter"
version = "0.4.13"
edition = "2021"
authors = [
    "Waylon Jepsen <waylonjepsen1@gmail.com>",
    "Colin Roberts <colin@autoparallel.xyz>",
]
description = "Allowing smart contract developers to do simulation driven development via an EVM emulator"
license = "Apache-2.0"
keywords = ["ethereum", "evm", "emulator", "testing", "smart-contracts"]

# Binary configuration
[[bin]]
name = "arbiter"
path = "bin/main.rs"

[workspace.dependencies]
arbiter-bindings = { version = "*", path = "./arbiter-bindings" }
arbiter-core = { version = "*", path = "./arbiter-core" }
ethers = { version = "2.0.11" }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = { version = "1.0.113" }
revm = { git = "https://github.com/bluealloy/revm.git", features = [
    "ethersdb",
    "std",
    "serde",
], rev = "30bbcdfe81446c9d1e9b37acc95f208943ddf858" }
revm-primitives = { git = "https://github.com/bluealloy/revm.git", rev = "30bbcdfe81446c9d1e9b37acc95f208943ddf858" }
thiserror = { version = "1.0.55" }
syn = { version = "2.0.43" }
quote = { version = "1.0.35" }
proc-macro2 = { version = "1.0.78" }
tokio = { version = "1.35.1", features = ["macros", "full"] }
crossbeam-channel = { version = "0.5.11" }
futures-util = { version = "=0.3.30" }
async-trait = { version = "0.1.76" }
tracing = "0.1.40"
async-stream = "0.3.5"

# Dependencies for the release build
[dependencies]
arbiter-core.workspace = true

# Command line and config
clap = { version = "=4.4.18", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
config = { version = "=0.13.4" }
ethers.workspace = true
revm.workspace = true
toml = { version = "=0.8.8" }
proc-macro2.workspace = true
syn.workspace = true
Inflector = { version = "=0.11.4" }

# Building files
quote.workspace = true
foundry-config = { version = "=0.2.0" }
tempfile = { version = "3.9.0" }

# Errors
thiserror.workspace = true
# Dependencies for the test build and development
[dev-dependencies]
tokio.workspace = true
assert_cmd = { version = "=2.0.13" }
rayon = { version = "1.8.0" }
revm-primitives.workspace = true

# Release profile
[profile.release]
# Link-Time Optimization can improve runtime at cost of build time
lto = true
# The Rust compiler splits your crate into multiple codegen units to parallelize (and thus speed up) compilation but at the cost of optimization. 
# This setting tells the compiler to use only one codegen unit, which will slow down compilation but improve optimization.
codegen-units = 1
